[package]
name = "canvas"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
gemgui = {path  = "../../gemgui" }

[dependencies]
gemgui = {path  = "../../gemgui" }
bytes = "1.3.0"

[[bin]]
name = "canvas"
path = "main.rs"
